-- The indicator catalogue (spec.md, «Catálogo de indicadores»).
INSERT INTO model.indicator VALUES
  ('hpi', 'Variación del precio de la vivienda', 'prices', 'index', 'Índice (2015 = 100)', [0],
    '[{"id": "total", "label": "Todas las viviendas"}, {"id": "new", "label": "Vivienda nueva"}, {"id": "existing", "label": "Vivienda existente"}]',
    NULL, 'prc_hpi_a', '{"purchase": ["TOTAL", "DW_NEW", "DW_EXST"], "unit": ["I25_A_AVG"]}', NULL,
    'Eurostat no publica el índice de Grecia.'),
  ('rent', 'Variación del alquiler', 'prices', 'index', 'Índice (2015 = 100)', [0],
    '[{"id": "total", "label": "Total"}]',
    NULL, 'prc_hicp_ainr', '{"coicop18": ["CP0411"], "unit": ["INX_A_AVG"]}', NULL,
    'Alquileres pagados por los inquilinos por su vivienda principal, incluidos los regulados y sociales: no es el precio de mercado.'),
  ('price_income', 'Precio de la vivienda frente a renta', 'prices', 'derived', 'Índice (2015 = 100)', [0],
    '[{"id": "total", "label": "Total"}]',
    NULL, 'prc_hpi_a, nama_10r_2hhinc', '{"purchase": ["TOTAL"], "unit": ["MIO_NAC", "MIO_EUR", "EUR_HAB"]}', NULL,
    'Elaboración propia: índice de precios de la vivienda entre índice de renta disponible por habitante en moneda nacional, ambos con base 2015.'),
  ('overburden', 'Sobrecarga por coste de vivienda', 'access', 'scalar', '%', [0],
    -- Opens on those who pay rent or a mortgage: the whole population, diluted by outright owners,
    -- stays last as the reference Eurostat uses.
    '[{"id": "rent_mkt", "label": "Inquilinos a precio de mercado"}, {"id": "rent", "label": "Todos los inquilinos (cálculo propio)"}, {"id": "own_l", "label": "Propietarios con hipoteca"}, {"id": "rent_fr", "label": "Inquilinos con alquiler reducido o gratuito"}, {"id": "youth", "label": "Jóvenes de 20 a 29 años"}, {"id": "own_nl", "label": "Propietarios sin hipoteca"}, {"id": "total", "label": "Toda la población"}]',
    NULL, 'ilc_lvho07a, ilc_lvho07c', '{"age": ["TOTAL", "Y20-29"], "sex": ["T"], "tenure": ["OWN_L", "OWN_NL", "RENT_MKT", "RENT_FR"]}', NULL,
    'Población que vive en hogares que dedican más del 40 % de su renta disponible a la vivienda.'),
  ('tenure', 'Régimen de tenencia', 'access', 'composition', '%', [0],
    '[{"id": "total", "label": "Total"}]',
    '[{"id": "own_l", "label": "Propietarios con hipoteca"}, {"id": "own_nl", "label": "Propietarios sin hipoteca"}, {"id": "rent_mkt", "label": "Inquilinos a precio de mercado"}, {"id": "rent_fr", "label": "Inquilinos con alquiler reducido o gratuito"}]',
    'ilc_lvho02', '{"tenure": ["OWN_L", "OWN_NL", "RENT_MKT", "RENT_FR", "RENT"]}',
    '{"id": "rent", "label": "Inquilinos (mercado y reducido)"}',
    'El mapa pinta el alquiler total (mercado más reducido). Países Bajos reclasifica en 2021 el alquiler social de mercado a reducido.'),
  ('emancipation', 'Edad media de emancipación', 'access', 'scalar', 'años', [0],
    '[{"id": "total", "label": "Total"}, {"id": "women", "label": "Mujeres"}, {"id": "men", "label": "Hombres"}]',
    NULL, 'yth_demo_030', '{"sex": ["T", "F", "M"]}', NULL,
    'Estimación de Eurostat de la edad a la que los jóvenes dejan el hogar familiar.'),
  ('unemployment', 'Tasa de paro', 'context', 'scalar', '%', [0, 2],
    '[{"id": "total", "label": "Total"}]',
    NULL, 'lfst_r_lfu3rt', '{"age": ["Y15-74"], "sex": ["T"], "isced11": ["TOTAL"]}', NULL,
    'Población activa de 15 a 74 años.'),
  ('income', 'Renta disponible de los hogares por habitante', 'context', 'scalar', 'PPS por habitante', [0, 2],
    '[{"id": "total", "label": "Total"}]',
    NULL, 'nama_10r_2hhinc', '{"unit": ["PPS_EU27_2020_HAB"], "na_item": ["B6N"]}', NULL,
    'En paridad de poder de compra, para comparar entre países. Último año completo: 2023.'),
  ('tourism', 'Intensidad turística', 'context', 'scalar', 'noches por habitante', [0, 2],
    '[{"id": "total", "label": "Total"}]',
    NULL, 'tour_occ_nin2', '{"unit": ["P_THAB"], "nace_r2": ["I551-I553"], "c_resid": ["TOTAL"]}', NULL,
    'Noches en alojamientos turísticos por habitante. Caída en 2020–2021 por la pandemia.'),
  ('popgrowth', 'Crecimiento de la población', 'context', 'scalar', '‰', [0, 2],
    '[{"id": "total", "label": "Crecimiento total"}, {"id": "migration", "label": "Saldo migratorio"}]',
    NULL, 'demo_r_gind3', '{"indic_de": ["GROWRT", "CNMIGRATRT"]}', NULL,
    'Eurostat no publica la media de la UE.');
